package com.example.Contrat;

/**
* Contrat/EtudiantHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contrat.idl
* Wednesday, December 25, 2024 5:37:51 PM WAT
*/

public final class EtudiantHolder implements org.omg.CORBA.portable.Streamable
{
  public Etudiant value = null;

  public EtudiantHolder ()
  {
  }

  public EtudiantHolder (Etudiant initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = EtudiantHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    EtudiantHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return EtudiantHelper.type ();
  }

}
