package com.example.Contrat;


/**
* Contrat/PromotionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contrat.idl
* Wednesday, December 25, 2024 5:37:51 PM WAT
*/

public interface PromotionOperations 
{
  void ajouter_un_etudiant (String nom, String prenom, int numero);
  Etudiant rechercher_un_etudiant (int numero);
  double calculer_moyenne_de_la_promotion ();
} // interface PromotionOperations
