// This file is generated by omniidl (C++ backend) - omniORB_4_3. Do not edit.

#include "Contrat.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

OMNI_MAYBE_UNUSED static const char* _0RL_library_version = omniORB_4_3;



Contrat::Etudiant_ptr Contrat::Etudiant_Helper::_nil() {
  return ::Contrat::Etudiant::_nil();
}

::CORBA::Boolean Contrat::Etudiant_Helper::is_nil(::Contrat::Etudiant_ptr p) {
  return ::CORBA::is_nil(p);

}

void Contrat::Etudiant_Helper::release(::Contrat::Etudiant_ptr p) {
  ::CORBA::release(p);
}

void Contrat::Etudiant_Helper::marshalObjRef(::Contrat::Etudiant_ptr obj, cdrStream& s) {
  ::Contrat::Etudiant::_marshalObjRef(obj, s);
}

Contrat::Etudiant_ptr Contrat::Etudiant_Helper::unmarshalObjRef(cdrStream& s) {
  return ::Contrat::Etudiant::_unmarshalObjRef(s);
}

void Contrat::Etudiant_Helper::duplicate(::Contrat::Etudiant_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

Contrat::Etudiant_ptr
Contrat::Etudiant::_duplicate(::Contrat::Etudiant_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

Contrat::Etudiant_ptr
Contrat::Etudiant::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


Contrat::Etudiant_ptr
Contrat::Etudiant::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

Contrat::Etudiant_ptr
Contrat::Etudiant::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_Etudiant _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_Etudiant* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_Etudiant;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* Contrat::Etudiant::_PD_repoId = "IDL:Contrat/Etudiant:1.0";


Contrat::_objref_Etudiant::~_objref_Etudiant() {
  
}


Contrat::_objref_Etudiant::_objref_Etudiant(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::Contrat::Etudiant::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
Contrat::_objref_Etudiant::_ptrToObjRef(const char* id)
{
  if (id == ::Contrat::Etudiant::_PD_repoId)
    return (::Contrat::Etudiant_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::Contrat::Etudiant::_PD_repoId))
    return (::Contrat::Etudiant_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for Contrat::Etudiant::Ajouter_une_epreuve

// Proxy call descriptor class. Mangled signature:
//  void_i_cstring_i_cdouble_i_cdouble
class _0RL_cd_bf8c361f7a5cfb57_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_bf8c361f7a5cfb57_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  ::CORBA::Double arg_1;
  ::CORBA::Double arg_2;
};

void _0RL_cd_bf8c361f7a5cfb57_00000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);
  arg_1 >>= _n;
  arg_2 >>= _n;

}

void _0RL_cd_bf8c361f7a5cfb57_00000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();
  (::CORBA::Double&)arg_1 <<= _n;
  (::CORBA::Double&)arg_2 <<= _n;

}

const char* const _0RL_cd_bf8c361f7a5cfb57_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_bf8c361f7a5cfb57_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_bf8c361f7a5cfb57_00000000* tcd = (_0RL_cd_bf8c361f7a5cfb57_00000000*)cd;
  Contrat::_impl_Etudiant* impl = (Contrat::_impl_Etudiant*) svnt->_ptrToInterface(Contrat::Etudiant::_PD_repoId);
  impl->Ajouter_une_epreuve(tcd->arg_0, tcd->arg_1, tcd->arg_2);


}

void Contrat::_objref_Etudiant::Ajouter_une_epreuve(const char* nom, ::CORBA::Double note, ::CORBA::Double coefficient)
{
  _0RL_cd_bf8c361f7a5cfb57_00000000 _call_desc(_0RL_lcfn_bf8c361f7a5cfb57_10000000, "Ajouter_une_epreuve", 20);
  _call_desc.arg_0 = nom;
  _call_desc.arg_1 = note;
  _call_desc.arg_2 = coefficient;

  _invoke(_call_desc);



}


//
// Code for Contrat::Etudiant::Liste_des_epreuves

// Proxy call descriptor class. Mangled signature:
//  _cContrat_mStringSequence
class _0RL_cd_bf8c361f7a5cfb57_20000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_bf8c361f7a5cfb57_20000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  Contrat::StringSequence_var result;
};

void _0RL_cd_bf8c361f7a5cfb57_20000000::marshalReturnedValues(cdrStream& _n)
{
  (const Contrat::StringSequence&) result >>= _n;

}

void _0RL_cd_bf8c361f7a5cfb57_20000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new Contrat::StringSequence;
  (Contrat::StringSequence&)result <<= _n;

}

const char* const _0RL_cd_bf8c361f7a5cfb57_20000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_bf8c361f7a5cfb57_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_bf8c361f7a5cfb57_20000000* tcd = (_0RL_cd_bf8c361f7a5cfb57_20000000*)cd;
  Contrat::_impl_Etudiant* impl = (Contrat::_impl_Etudiant*) svnt->_ptrToInterface(Contrat::Etudiant::_PD_repoId);
  tcd->result = impl->Liste_des_epreuves();


}

Contrat::StringSequence* Contrat::_objref_Etudiant::Liste_des_epreuves()
{
  _0RL_cd_bf8c361f7a5cfb57_20000000 _call_desc(_0RL_lcfn_bf8c361f7a5cfb57_30000000, "Liste_des_epreuves", 19);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for Contrat::Etudiant::Liste_des_livres

// Local call call-back function.
static void
_0RL_lcfn_bf8c361f7a5cfb57_40000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_bf8c361f7a5cfb57_20000000* tcd = (_0RL_cd_bf8c361f7a5cfb57_20000000*)cd;
  Contrat::_impl_Etudiant* impl = (Contrat::_impl_Etudiant*) svnt->_ptrToInterface(Contrat::Etudiant::_PD_repoId);
  tcd->result = impl->Liste_des_livres();


}

Contrat::StringSequence* Contrat::_objref_Etudiant::Liste_des_livres()
{
  _0RL_cd_bf8c361f7a5cfb57_20000000 _call_desc(_0RL_lcfn_bf8c361f7a5cfb57_40000000, "Liste_des_livres", 17);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for Contrat::Etudiant::Calculer_la_moyenne

// Proxy call descriptor class. Mangled signature:
//  _cdouble
class _0RL_cd_bf8c361f7a5cfb57_50000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_bf8c361f7a5cfb57_50000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Double result;
};

void _0RL_cd_bf8c361f7a5cfb57_50000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_bf8c361f7a5cfb57_50000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Double&)result <<= _n;

}

const char* const _0RL_cd_bf8c361f7a5cfb57_50000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_bf8c361f7a5cfb57_60000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_bf8c361f7a5cfb57_50000000* tcd = (_0RL_cd_bf8c361f7a5cfb57_50000000*)cd;
  Contrat::_impl_Etudiant* impl = (Contrat::_impl_Etudiant*) svnt->_ptrToInterface(Contrat::Etudiant::_PD_repoId);
  tcd->result = impl->Calculer_la_moyenne();


}

::CORBA::Double Contrat::_objref_Etudiant::Calculer_la_moyenne()
{
  _0RL_cd_bf8c361f7a5cfb57_50000000 _call_desc(_0RL_lcfn_bf8c361f7a5cfb57_60000000, "Calculer_la_moyenne", 20);


  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for Contrat::Etudiant::Emprunter_un_livre

// Proxy call descriptor class. Mangled signature:
//  void_i_cstring_i_cstring_i_cstring_i_cstring
class _0RL_cd_bf8c361f7a5cfb57_70000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_bf8c361f7a5cfb57_70000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  ::CORBA::String_var arg_1_;
  const char* arg_1;
  ::CORBA::String_var arg_2_;
  const char* arg_2;
  ::CORBA::String_var arg_3_;
  const char* arg_3;
};

void _0RL_cd_bf8c361f7a5cfb57_70000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);
  _n.marshalString(arg_1,0);
  _n.marshalString(arg_2,0);
  _n.marshalString(arg_3,0);

}

void _0RL_cd_bf8c361f7a5cfb57_70000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();
  arg_1_ = _n.unmarshalString(0);
  arg_1 = arg_1_.in();
  arg_2_ = _n.unmarshalString(0);
  arg_2 = arg_2_.in();
  arg_3_ = _n.unmarshalString(0);
  arg_3 = arg_3_.in();

}

const char* const _0RL_cd_bf8c361f7a5cfb57_70000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_bf8c361f7a5cfb57_80000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_bf8c361f7a5cfb57_70000000* tcd = (_0RL_cd_bf8c361f7a5cfb57_70000000*)cd;
  Contrat::_impl_Etudiant* impl = (Contrat::_impl_Etudiant*) svnt->_ptrToInterface(Contrat::Etudiant::_PD_repoId);
  impl->Emprunter_un_livre(tcd->arg_0, tcd->arg_1, tcd->arg_2, tcd->arg_3);


}

void Contrat::_objref_Etudiant::Emprunter_un_livre(const char* nom, const char* auteur, const char* collection, const char* datePublication)
{
  _0RL_cd_bf8c361f7a5cfb57_70000000 _call_desc(_0RL_lcfn_bf8c361f7a5cfb57_80000000, "Emprunter_un_livre", 19);
  _call_desc.arg_0 = nom;
  _call_desc.arg_1 = auteur;
  _call_desc.arg_2 = collection;
  _call_desc.arg_3 = datePublication;

  _invoke(_call_desc);



}

Contrat::_pof_Etudiant::~_pof_Etudiant() {}


omniObjRef*
Contrat::_pof_Etudiant::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::Contrat::_objref_Etudiant(ior, id);
}


::CORBA::Boolean
Contrat::_pof_Etudiant::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::Contrat::Etudiant::_PD_repoId))
    return 1;
  
  return 0;
}

const Contrat::_pof_Etudiant _the_pof_Contrat_mEtudiant;

Contrat::_impl_Etudiant::~_impl_Etudiant() {}


::CORBA::Boolean
Contrat::_impl_Etudiant::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "Ajouter_une_epreuve")) {

    _0RL_cd_bf8c361f7a5cfb57_00000000 _call_desc(_0RL_lcfn_bf8c361f7a5cfb57_10000000, "Ajouter_une_epreuve", 20, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "Liste_des_epreuves")) {

    _0RL_cd_bf8c361f7a5cfb57_20000000 _call_desc(_0RL_lcfn_bf8c361f7a5cfb57_30000000, "Liste_des_epreuves", 19, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "Liste_des_livres")) {

    _0RL_cd_bf8c361f7a5cfb57_20000000 _call_desc(_0RL_lcfn_bf8c361f7a5cfb57_40000000, "Liste_des_livres", 17, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "Calculer_la_moyenne")) {

    _0RL_cd_bf8c361f7a5cfb57_50000000 _call_desc(_0RL_lcfn_bf8c361f7a5cfb57_60000000, "Calculer_la_moyenne", 20, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "Emprunter_un_livre")) {

    _0RL_cd_bf8c361f7a5cfb57_70000000 _call_desc(_0RL_lcfn_bf8c361f7a5cfb57_80000000, "Emprunter_un_livre", 19, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
Contrat::_impl_Etudiant::_ptrToInterface(const char* id)
{
  if (id == ::Contrat::Etudiant::_PD_repoId)
    return (::Contrat::_impl_Etudiant*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::Contrat::Etudiant::_PD_repoId))
    return (::Contrat::_impl_Etudiant*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
Contrat::_impl_Etudiant::_mostDerivedRepoId()
{
  return ::Contrat::Etudiant::_PD_repoId;
}

Contrat::Promotion_ptr Contrat::Promotion_Helper::_nil() {
  return ::Contrat::Promotion::_nil();
}

::CORBA::Boolean Contrat::Promotion_Helper::is_nil(::Contrat::Promotion_ptr p) {
  return ::CORBA::is_nil(p);

}

void Contrat::Promotion_Helper::release(::Contrat::Promotion_ptr p) {
  ::CORBA::release(p);
}

void Contrat::Promotion_Helper::marshalObjRef(::Contrat::Promotion_ptr obj, cdrStream& s) {
  ::Contrat::Promotion::_marshalObjRef(obj, s);
}

Contrat::Promotion_ptr Contrat::Promotion_Helper::unmarshalObjRef(cdrStream& s) {
  return ::Contrat::Promotion::_unmarshalObjRef(s);
}

void Contrat::Promotion_Helper::duplicate(::Contrat::Promotion_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

Contrat::Promotion_ptr
Contrat::Promotion::_duplicate(::Contrat::Promotion_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

Contrat::Promotion_ptr
Contrat::Promotion::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


Contrat::Promotion_ptr
Contrat::Promotion::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

Contrat::Promotion_ptr
Contrat::Promotion::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_Promotion _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_Promotion* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_Promotion;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* Contrat::Promotion::_PD_repoId = "IDL:Contrat/Promotion:1.0";


Contrat::_objref_Promotion::~_objref_Promotion() {
  
}


Contrat::_objref_Promotion::_objref_Promotion(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::Contrat::Promotion::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
Contrat::_objref_Promotion::_ptrToObjRef(const char* id)
{
  if (id == ::Contrat::Promotion::_PD_repoId)
    return (::Contrat::Promotion_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::Contrat::Promotion::_PD_repoId))
    return (::Contrat::Promotion_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for Contrat::Promotion::ajouter_un_etudiant

// Proxy call descriptor class. Mangled signature:
//  void_i_cstring_i_cstring_i_clong
class _0RL_cd_bf8c361f7a5cfb57_90000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_bf8c361f7a5cfb57_90000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  ::CORBA::String_var arg_1_;
  const char* arg_1;
  ::CORBA::Long arg_2;
};

void _0RL_cd_bf8c361f7a5cfb57_90000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);
  _n.marshalString(arg_1,0);
  arg_2 >>= _n;

}

void _0RL_cd_bf8c361f7a5cfb57_90000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();
  arg_1_ = _n.unmarshalString(0);
  arg_1 = arg_1_.in();
  (::CORBA::Long&)arg_2 <<= _n;

}

const char* const _0RL_cd_bf8c361f7a5cfb57_90000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_bf8c361f7a5cfb57_a0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_bf8c361f7a5cfb57_90000000* tcd = (_0RL_cd_bf8c361f7a5cfb57_90000000*)cd;
  Contrat::_impl_Promotion* impl = (Contrat::_impl_Promotion*) svnt->_ptrToInterface(Contrat::Promotion::_PD_repoId);
  impl->ajouter_un_etudiant(tcd->arg_0, tcd->arg_1, tcd->arg_2);


}

void Contrat::_objref_Promotion::ajouter_un_etudiant(const char* nom, const char* prenom, ::CORBA::Long numero)
{
  _0RL_cd_bf8c361f7a5cfb57_90000000 _call_desc(_0RL_lcfn_bf8c361f7a5cfb57_a0000000, "ajouter_un_etudiant", 20);
  _call_desc.arg_0 = nom;
  _call_desc.arg_1 = prenom;
  _call_desc.arg_2 = numero;

  _invoke(_call_desc);



}


//
// Code for Contrat::Promotion::rechercher_un_etudiant

// Proxy call descriptor class. Mangled signature:
//  _cContrat_mEtudiant_i_clong
class _0RL_cd_bf8c361f7a5cfb57_b0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_bf8c361f7a5cfb57_b0000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Long arg_0;
  Contrat::Etudiant_var result;
};

void _0RL_cd_bf8c361f7a5cfb57_b0000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_bf8c361f7a5cfb57_b0000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Long&)arg_0 <<= _n;

}

void _0RL_cd_bf8c361f7a5cfb57_b0000000::marshalReturnedValues(cdrStream& _n)
{
  Contrat::Etudiant::_marshalObjRef(result,_n);

}

void _0RL_cd_bf8c361f7a5cfb57_b0000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = Contrat::Etudiant::_unmarshalObjRef(_n);

}

const char* const _0RL_cd_bf8c361f7a5cfb57_b0000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_bf8c361f7a5cfb57_c0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_bf8c361f7a5cfb57_b0000000* tcd = (_0RL_cd_bf8c361f7a5cfb57_b0000000*)cd;
  Contrat::_impl_Promotion* impl = (Contrat::_impl_Promotion*) svnt->_ptrToInterface(Contrat::Promotion::_PD_repoId);
  tcd->result = impl->rechercher_un_etudiant(tcd->arg_0);


}

Contrat::Etudiant_ptr Contrat::_objref_Promotion::rechercher_un_etudiant(::CORBA::Long numero)
{
  _0RL_cd_bf8c361f7a5cfb57_b0000000 _call_desc(_0RL_lcfn_bf8c361f7a5cfb57_c0000000, "rechercher_un_etudiant", 23);
  _call_desc.arg_0 = numero;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for Contrat::Promotion::calculer_moyenne_de_la_promotion

// Local call call-back function.
static void
_0RL_lcfn_bf8c361f7a5cfb57_d0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_bf8c361f7a5cfb57_50000000* tcd = (_0RL_cd_bf8c361f7a5cfb57_50000000*)cd;
  Contrat::_impl_Promotion* impl = (Contrat::_impl_Promotion*) svnt->_ptrToInterface(Contrat::Promotion::_PD_repoId);
  tcd->result = impl->calculer_moyenne_de_la_promotion();


}

::CORBA::Double Contrat::_objref_Promotion::calculer_moyenne_de_la_promotion()
{
  _0RL_cd_bf8c361f7a5cfb57_50000000 _call_desc(_0RL_lcfn_bf8c361f7a5cfb57_d0000000, "calculer_moyenne_de_la_promotion", 33);


  _invoke(_call_desc);
  return _call_desc.result;


}

Contrat::_pof_Promotion::~_pof_Promotion() {}


omniObjRef*
Contrat::_pof_Promotion::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::Contrat::_objref_Promotion(ior, id);
}


::CORBA::Boolean
Contrat::_pof_Promotion::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::Contrat::Promotion::_PD_repoId))
    return 1;
  
  return 0;
}

const Contrat::_pof_Promotion _the_pof_Contrat_mPromotion;

Contrat::_impl_Promotion::~_impl_Promotion() {}


::CORBA::Boolean
Contrat::_impl_Promotion::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "ajouter_un_etudiant")) {

    _0RL_cd_bf8c361f7a5cfb57_90000000 _call_desc(_0RL_lcfn_bf8c361f7a5cfb57_a0000000, "ajouter_un_etudiant", 20, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "rechercher_un_etudiant")) {

    _0RL_cd_bf8c361f7a5cfb57_b0000000 _call_desc(_0RL_lcfn_bf8c361f7a5cfb57_c0000000, "rechercher_un_etudiant", 23, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "calculer_moyenne_de_la_promotion")) {

    _0RL_cd_bf8c361f7a5cfb57_50000000 _call_desc(_0RL_lcfn_bf8c361f7a5cfb57_d0000000, "calculer_moyenne_de_la_promotion", 33, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
Contrat::_impl_Promotion::_ptrToInterface(const char* id)
{
  if (id == ::Contrat::Promotion::_PD_repoId)
    return (::Contrat::_impl_Promotion*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::Contrat::Promotion::_PD_repoId))
    return (::Contrat::_impl_Promotion*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
Contrat::_impl_Promotion::_mostDerivedRepoId()
{
  return ::Contrat::Promotion::_PD_repoId;
}

POA_Contrat::Etudiant::~Etudiant() {}

POA_Contrat::Promotion::~Promotion() {}

